spring:
  application:
    name: worldservice
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.cert

opentracing:
  jaeger:
    http-sender:
      url: http://jaeger-collector.istio-system:14268/api/traces
